condominium_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("votacoes/", include("votacoes.urls")),
    path('admin/', admin.site.urls),
]

votacoes/urls.py
from django.urls import path

from . import views

app_name = "votacoes"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detalhe"),
    path("<int:pk>/resultados/", views.ResultsView.as_view(), name="resultados"),
    path("<int:question_id>/voto/", views.vote, name="voto"),
]

votacoes/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("data publicada")

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

votacoes/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Question, Choice


# Create your views here.
class IndexView(generic.ListView):
    template_name = "votacoes/index.html"
    context_object_name = "latest_question_list"
    def get_queryset(self):
        """Retornar as cinco últimas questões publicadas"""
        return Question.objects.order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = "votacoes/detail.html"

class ResultsView(generic.DetailView):
    model = Question
    template_name = "votacoes/results.html"
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice =question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            "votacoes/detail.html",
            {
                "question": question,
                "error_message": "Você não fez uma escolha"
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse("votacoes:resultados", args=(question.id,)))

votacoes/templates/votacoes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Questões</title>
</head>
<body>
{% load static %}

<link rel="stylesheet" href="{% static 'votacoes/style.css' %}">


<form action="{% url 'votacoes:voto' question.id %}" method="post">{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}
        </label><br>
    {% endfor %}
</fieldset>
    <input type="submit" value="Votar">
</form>
</ul>

</body>
</html>

votacoes/templates/votacoes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Condominium Manager</title>
</head>
<body>
{% load static %}

<link rel="stylesheet" href="{% static 'votacoes/style.css' %}">


    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'votacoes:detalhe' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Não há votações disponíveis.</p>
{% endif %}
</body>
</html>

votacoes/templates/votacoes/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Resultados</title>
</head>
<body>
{% load static %}

<link rel="stylesheet" href="{% static 'votacoes/style.css' %}">


<h1>{{ question.question_text }}</h1>

<ul>
  {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
  {% endfor %}
</ul>

<a href="{% url 'votacoes:detalhe' question.id %}">Votar novamente?</a>
</body>
</html>